[versions]
agp = "8.6.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
datastoreCoreAndroid = "1.1.1"
filamentAndroid = "1.17.1"
gamesActivity = "3.0.5"
media3Common = "1.4.1"
junitJupiter = "5.8.1"
playServicesVision = "20.1.3"
visionCommon = "17.3.0"
datastorePreferencesCoreJvm = "1.1.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
datastore-core-android = { group = "androidx.datastore", name = "datastore-core-android", version.ref = "datastoreCoreAndroid" }
datastore-preferences-core-jvm = { group = "androidx.datastore", name = "datastore-preferences-core-jvm", version.ref = "datastorePreferencesCoreJvm" }
filament-android = { group = "com.google.ar.sceneform", name = "filament-android", version.ref = "filamentAndroid" }
games-activity = { group = "androidx.games", name = "games-activity", version.ref = "gamesActivity" }
media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3Common" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
play-services-vision = { group = "com.google.android.gms", name = "play-services-vision", version.ref = "playServicesVision" }
vision-common = { group = "com.google.mlkit", name = "vision-common", version.ref = "visionCommon" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

